---
data_params:
  - provider: vires
    collection: "SW_OPER_MAGB_LR_1B"
    measurements: ["B_NEC"]
    models: ["IGRF"]
    start_time: "2016-01-01T00:00:00"
    end_time: "2016-01-01T00:01:00"
    server_url: "https://vires.services/ows"
