---
# Datasets for tests/io/test_paldata.py
data_params:
  - provider: vires
    collection: "SW_OPER_MAGA_LR_1B"
    measurements: ["F", "B_NEC"]
    start_time: "2016-01-01T00:00:00"
    end_time: "2016-01-01T00:00:10"
    models: ["IGRF"]
    filters: ["(Longitude > 92.8) AND (Latitude < -72.57)"]
