---
data_params:
  - provider: vires
    collection: "SW_OPER_MAGA_LR_1B"
    measurements: ["B_NEC"]
    models: ["CHAOS"]
    start_time: "2016-01-01T00:00:00"
    end_time: "2016-01-01T00:30:00"
    server_url: "https://vires.services/ows"
process_params:
  - process_name: FAC_single_sat
    dataset: SW_OPER_MAGA_LR_1B
    model_varname: B_NEC_CHAOS
    measurement_varname: B_NEC
    inclination_limit: 30
    time_jump_limit: 6
